// <auto-generated />
using System;
using System.Collections.Generic;
using Clubber.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clubber.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clubber")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clubber.Domain.Data.Entities.DdNewsItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ItemId"));

                    b.Property<long>("LeaderboardId")
                        .HasColumnType("bigint");

                    b.Property<int>("Nth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOfOccurenceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewEntry", "Clubber.Domain.Data.Entities.DdNewsItem.NewEntry#EntryResponse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DaggersFired")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DaggersFiredTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("DaggersHit")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DaggersHitTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("DeathType")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DeathsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("Gems")
                                .HasColumnType("integer");

                            b1.Property<decimal>("GemsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<int>("Kills")
                                .HasColumnType("integer");

                            b1.Property<decimal>("KillsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer");

                            b1.Property<int>("Time")
                                .HasColumnType("integer");

                            b1.Property<decimal>("TimeTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OldEntry", "Clubber.Domain.Data.Entities.DdNewsItem.OldEntry#EntryResponse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DaggersFired")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DaggersFiredTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("DaggersHit")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DaggersHitTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("DeathType")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DeathsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("Gems")
                                .HasColumnType("integer");

                            b1.Property<decimal>("GemsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<long>("Id")
                                .HasColumnType("bigint");

                            b1.Property<int>("Kills")
                                .HasColumnType("integer");

                            b1.Property<decimal>("KillsTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer");

                            b1.Property<int>("Time")
                                .HasColumnType("integer");

                            b1.Property<decimal>("TimeTotal")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("ItemId");

                    b.ToTable("DdNews", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.DdSplits.BestSplit", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GameInfo", "Clubber.Domain.Data.Entities.DdSplits.BestSplit.GameInfo#GameInfo", b1 =>
                        {
                            b1.Property<double>("Accuracy")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("accuracy");

                            b1.Property<int>("DaggersFired")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("daggers_fired");

                            b1.Property<int>("DaggersHit")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("daggers_hit");

                            b1.Property<string>("DeathType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasJsonPropertyName("death_type");

                            b1.Property<int>("EnemiesAlive")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("enemies_alive");

                            b1.Property<int>("EnemiesAliveMax")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("enemies_alive_max");

                            b1.Property<double>("EnemiesAliveMaxTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("enemies_alive_max_time");

                            b1.Property<int>("EnemiesKilled")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("enemies_killed");

                            b1.Property<float>("GameTime")
                                .HasColumnType("real")
                                .HasJsonPropertyName("game_time");

                            b1.Property<int>("Gems")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("gems");

                            b1.Property<int>("Granularity")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("granularity");

                            b1.Property<int>("HomingDaggers")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("homing_daggers");

                            b1.Property<int>("HomingDaggersMax")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("homing_daggers_max");

                            b1.Property<double>("HomingDaggersMaxTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("homing_daggers_max_time");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("id");

                            b1.Property<bool>("IsReplay")
                                .HasColumnType("boolean")
                                .HasJsonPropertyName("is_replay");

                            b1.Property<double>("LevelFourTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("level_four_time");

                            b1.Property<double>("LevelThreeTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("level_three_time");

                            b1.Property<double>("LevelTwoTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("level_two_time");

                            b1.Property<double>("LeviDownTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("levi_down_time");

                            b1.Property<double>("OrbDownTime")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("orb_down_time");

                            b1.Property<int>("PlayerGameTime")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("player_game_time");

                            b1.Property<long>("PlayerId")
                                .HasColumnType("bigint")
                                .HasJsonPropertyName("player_id");

                            b1.Property<string>("PlayerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasJsonPropertyName("player_name");

                            b1.Property<int>("ReplayPlayerId")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("replay_player_id");

                            b1.Property<string>("ReplayPlayerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasJsonPropertyName("replay_player_name");

                            b1.Property<string>("Spawnset")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasJsonPropertyName("spawnset");

                            b1.Property<DateTime>("TimeStamp")
                                .HasColumnType("timestamp with time zone")
                                .HasJsonPropertyName("time_stamp");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasJsonPropertyName("version");
                        });

                    b.HasKey("Name");

                    b.ToTable("BestSplits", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.DdSplits.HomingPeakRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomingPeak")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerLeaderboardId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TopHomingPeaks", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.DdUser", b =>
                {
                    b.Property<decimal>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("LeaderboardId")
                        .HasColumnType("bigint");

                    b.Property<string>("TwitchUsername")
                        .HasColumnType("text");

                    b.HasKey("DiscordId");

                    b.HasIndex("LeaderboardId");

                    b.ToTable("DdPlayers", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.HundredthCount", b =>
                {
                    b.Property<int>("Threshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Threshold"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Threshold");

                    b.ToTable("HundredthCounts", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.NewsCursor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NewsCursors", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.PlayerPb", b =>
                {
                    b.Property<long>("LeaderboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LeaderboardId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaderboardId");

                    b.ToTable("PlayerPbs", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.RankRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("RankRoles", "clubber");
                });

            modelBuilder.Entity("Clubber.Domain.Data.Entities.ScoreRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("ScoreRoles", "clubber");
                });
#pragma warning restore 612, 618
        }
    }
}
